apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  LOG_LEVEL: "{{ .Values.logLevel }}"
  DATABASE_HOST: "{{ .Values.database.host }}"
  DATABASE_PORT: "{{ .Values.database.port }}"
  DATABASE_NAME: "{{ .Values.database.name }}"
  GOOGLE_CLIENT_ID: "{{ .Values.nextAuth.providers.google.clientId }}"
  NEXTAUTH_URL: "{{ .Values.baseUrl }}"