apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
  GOOGLE_CLIENT_SECRET: "{{ .Values.nextAuth.providers.google.clientSecret }}"
  NEXTAUTH_SECRET: "{{ .Values.nextAuth.secret }}"
  DATABASE_USERNAME: "{{ .Values.database.username }}"
  DATABASE_PASSWORD: "{{ .Values.database.password }}"