name: Create Tag
on:
  push:
    branches:
      - main

jobs:
  common-create-tag:
    uses: unknorg/common-workflows/.github/workflows/create-tag.gen.yml@v0.6.3
    secrets:
      GITHUB_PAT: ${{ secrets.COMMON_PAT }}